apiVersion: apps/v1
kind: Deployment
metadata:
  name: htttp
  labels:
    app: htttp

spec:
  replicas: 20

  selector:
    matchLabels:
      app: htttp

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: htttp
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.18
